name: hexlet-check
on:
  [push]:
    branches:
      - master
      - main
      - workflow2
      - fix4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
